server:
  port: 8070
 
spring:
  application:
    name: cur-service
    
  main:
    allow-bean-definition-overriding: true


  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: welcome

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
