server:
  port: 8070
 
spring:
  application:
    name: image-service
    
 # h2:
 #   console:
  #    enabled: true
   #   settings:
    #    web-allow-others: true
     # path: /console
      
  data:
    mongodb:
      port: 27017
      database: user
      host: localhost
      
  main:
    allow-bean-definition-overriding: true
     

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

